# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/lab_05/.Xil/Vivado-20988-Reginald-Bayeta/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    d:/lab_05/lab_05.gen/sources_1/bd/zynq_base/ipshared/34f8/hdl
    d:/lab_05/lab_05.gen/sources_1/bd/zynq_base/ipshared/d0f7
    d:/lab_05/lab_05.gen/sources_1/bd/zynq_base/ipshared/ec67/hdl
  } {
      D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    d:/lab_05/lab_05.gen/sources_1/bd/zynq_base/ipshared/34f8/hdl
    d:/lab_05/lab_05.gen/sources_1/bd/zynq_base/ipshared/d0f7
    d:/lab_05/lab_05.gen/sources_1/bd/zynq_base/ipshared/ec67/hdl
  } {
      d:/lab_05/lab_05.gen/sources_1/bd/zynq_base/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v
      d:/lab_05/lab_05.gen/sources_1/bd/zynq_base/ip/zynq_base_xlslice_0_0/synth/zynq_base_xlslice_0_0.v
      d:/lab_05/lab_05.gen/sources_1/bd/zynq_base/ip/zynq_base_xlslice_red_0/synth/zynq_base_xlslice_red_0.v
      d:/lab_05/lab_05.gen/sources_1/bd/zynq_base/ip/zynq_base_xlslice_red1_1/synth/zynq_base_xlslice_red1_1.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      D:/lab_05/.Xil/Vivado-20988-Reginald-Bayeta/realtime/zynq_base_processing_system7_0_0_stub.vhdl
      D:/lab_05/.Xil/Vivado-20988-Reginald-Bayeta/realtime/zynq_base_clk_wiz_0_0_stub.vhdl
      D:/lab_05/.Xil/Vivado-20988-Reginald-Bayeta/realtime/zynq_base_v_tc_0_0_stub.vhdl
      D:/lab_05/.Xil/Vivado-20988-Reginald-Bayeta/realtime/zynq_base_v_axi4s_vid_out_0_0_stub.vhdl
      D:/lab_05/.Xil/Vivado-20988-Reginald-Bayeta/realtime/zynq_base_v_tpg_0_0_stub.vhdl
      D:/lab_05/.Xil/Vivado-20988-Reginald-Bayeta/realtime/zynq_base_auto_pc_0_stub.vhdl
      D:/lab_05/.Xil/Vivado-20988-Reginald-Bayeta/realtime/zynq_base_rst_clk_wiz_0_74M_0_stub.vhdl
      d:/lab_05/lab_05.gen/sources_1/bd/zynq_base/synth/zynq_base.vhd
      D:/lab_05/lab_05.gen/sources_1/bd/zynq_base/hdl/zynq_base_wrapper.vhd
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top zynq_base_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/lab_05/.Xil/Vivado-20988-Reginald-Bayeta/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
