// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module zynq_base_v_tpg_0_0_tpgForeground (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        srcImg_dout,
        srcImg_empty_n,
        srcImg_read,
        height,
        width,
        patternId,
        maskId,
        colorFormat,
        crossHairX,
        crossHairY,
        boxSize,
        boxColorR,
        boxColorG,
        boxColorB,
        motionSpeed,
        outImg_din,
        outImg_full_n,
        outImg_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state6 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [23:0] srcImg_dout;
input   srcImg_empty_n;
output   srcImg_read;
input  [15:0] height;
input  [15:0] width;
input  [7:0] patternId;
input  [7:0] maskId;
input  [7:0] colorFormat;
input  [15:0] crossHairX;
input  [15:0] crossHairY;
input  [15:0] boxSize;
input  [15:0] boxColorR;
input  [15:0] boxColorG;
input  [15:0] boxColorB;
input  [7:0] motionSpeed;
output  [23:0] outImg_din;
input   outImg_full_n;
output   outImg_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg srcImg_read;
reg outImg_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [15:0] boxHCoord;
reg   [15:0] boxVCoord;
reg   [0:0] hDir;
reg   [0:0] vDir;
wire   [1:0] whiYuv_2_address0;
reg    whiYuv_2_ce0;
wire   [7:0] whiYuv_2_q0;
reg    srcImg_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln746_reg_990;
reg    outImg_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln746_reg_990_pp0_iter1_reg;
reg   [15:0] x_reg_230;
wire   [7:0] patternId_read_read_fu_132_p2;
wire   [0:0] tobool_fu_341_p2;
wire   [15:0] hMax_fu_347_p2;
wire   [15:0] vMax_fu_353_p2;
wire   [0:0] cmp11_i106_fu_359_p2;
wire   [7:0] pixOut_fu_365_p3;
wire   [0:0] cmp13_i_fu_373_p2;
wire   [0:0] and4_i_fu_383_p2;
wire   [0:0] and10_i_fu_397_p2;
wire   [0:0] and24_i_fu_411_p2;
wire   [7:0] pixOut_4_fu_417_p1;
wire   [0:0] icmp_fu_431_p2;
wire   [7:0] pixOut_6_fu_437_p1;
wire   [15:0] zext_ln1867_1_fu_449_p1;
wire   [15:0] zext_ln1867_fu_453_p1;
wire   [1:0] select_ln1919_1_fu_465_p3;
wire   [15:0] y_1_fu_483_p2;
reg   [15:0] y_1_reg_966;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln744_fu_489_p2;
wire   [0:0] icmp_ln1913_fu_494_p2;
reg   [0:0] icmp_ln1913_reg_975;
wire   [15:0] x_1_fu_499_p2;
reg   [15:0] x_1_reg_980;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_state5_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln746_fu_505_p1;
reg   [0:0] trunc_ln746_reg_985;
wire   [0:0] icmp_ln746_fu_509_p2;
wire   [0:0] icmp_ln1840_fu_520_p2;
wire   [0:0] hDir_load_load_fu_526_p1;
wire   [0:0] icmp_ln1845_fu_533_p2;
wire   [0:0] icmp_ln1849_fu_544_p2;
wire   [0:0] and_ln1913_fu_621_p2;
reg   [0:0] and_ln1913_reg_1019;
wire   [0:0] or_ln1913_fu_626_p2;
reg   [0:0] or_ln1913_reg_1026;
wire   [7:0] pixOut_1_fu_648_p1;
wire   [7:0] pixOut_2_fu_652_p4;
wire   [7:0] pixOut_3_fu_662_p4;
wire   [0:0] and_ln1895_fu_736_p2;
wire   [7:0] pixOut_5_fu_749_p3;
wire   [7:0] select_ln1913_fu_756_p3;
wire   [7:0] select_ln1913_1_fu_762_p3;
wire   [7:0] select_ln1913_2_fu_769_p3;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg   [15:0] y_reg_218;
reg    ap_block_state1;
wire    ap_CS_fsm_state6;
reg   [15:0] ap_phi_mux_x_phi_fu_234_p4;
reg   [0:0] ap_phi_mux_empty_61_phi_fu_245_p8;
wire   [0:0] ap_phi_reg_pp0_iter0_empty_61_reg_242;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_reg_259;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_2_reg_259;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_reg_274;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_1_reg_274;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_reg_289;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_reg_289;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_val_V_reg_289;
wire   [63:0] zext_ln1919_fu_643_p1;
wire   [15:0] grp_fu_319_p3;
wire   [0:0] vDir_load_load_fu_555_p1;
wire   [0:0] icmp_ln1855_fu_562_p2;
wire   [0:0] icmp_ln1859_fu_573_p2;
wire   [15:0] sub_ln1871_fu_578_p2;
wire   [15:0] add_ln1869_fu_600_p2;
reg   [15:0] boxTop_fu_112;
reg   [15:0] boxLeft_fu_116;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] grp_fu_309_p2;
wire   [15:0] grp_fu_314_p2;
wire   [0:0] empty_fu_379_p1;
wire   [0:0] tmp_fu_389_p3;
wire   [0:0] tmp_1_fu_403_p3;
wire   [6:0] tmp_2_fu_421_p4;
wire   [8:0] shl_i_fu_441_p3;
wire   [15:0] or_ln1840_fu_514_p2;
wire   [0:0] icmp_ln1913_1_fu_616_p2;
wire   [0:0] or_ln1919_fu_631_p2;
wire   [1:0] select_ln1919_fu_636_p3;
wire   [0:0] ult_fu_688_p2;
wire   [15:0] boxBottom_fu_683_p2;
wire   [0:0] icmp_ln1890_fu_706_p2;
wire   [15:0] boxRight_fu_678_p2;
wire   [0:0] notrhs_fu_700_p2;
wire   [0:0] rev14_fu_694_p2;
wire   [0:0] icmp_ln1890_1_fu_718_p2;
wire   [0:0] xor_ln1890_fu_712_p2;
wire   [0:0] and_ln1895_2_fu_730_p2;
wire   [0:0] and_ln1895_1_fu_724_p2;
wire   [0:0] and_ln1899_fu_742_p2;
wire   [7:0] trunc_ln1899_fu_746_p1;
wire   [7:0] select_ln1937_fu_783_p3;
wire   [7:0] select_ln1933_fu_776_p3;
wire   [7:0] select_ln1935_fu_804_p3;
wire   [7:0] outpix_0_2_0_0_0_load_fu_790_p3;
wire   [7:0] empty_62_fu_811_p3;
wire   [7:0] outpix_0_0_0_0_0_load_fu_797_p3;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_365;
reg    ap_condition_368;
reg    ap_condition_182;
reg    ap_condition_717;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 boxHCoord = 16'd0;
#0 boxVCoord = 16'd0;
#0 hDir = 1'd0;
#0 vDir = 1'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

zynq_base_v_tpg_0_0_tpgForeground_whiYuv_2 #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
whiYuv_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(whiYuv_2_address0),
    .ce0(whiYuv_2_ce0),
    .q0(whiYuv_2_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln744_fu_489_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln744_fu_489_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln744_fu_489_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln1895_fu_736_p2) & (patternId_read_read_fu_132_p2 == 8'd1))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274 <= pixOut_5_fu_749_p3;
    end else if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln1913_reg_1026 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_read_read_fu_132_p2 == 8'd2))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274 <= whiYuv_2_q0;
    end else if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln1913_reg_1026 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_read_read_fu_132_p2 == 8'd2))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274 <= select_ln1913_1_fu_762_p3;
    end else if ((((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'd0 == and_ln1895_fu_736_p2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_read_read_fu_132_p2 == 8'd1)) | (~(patternId_read_read_fu_132_p2 == 8'd2) & ~(patternId_read_read_fu_132_p2 == 8'd1) & (icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274 <= {{srcImg_dout[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274 <= ap_phi_reg_pp0_iter1_pix_val_V_1_reg_274;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln1895_fu_736_p2) & (patternId_read_read_fu_132_p2 == 8'd1))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259 <= pixOut_6_fu_437_p1;
    end else if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln1913_reg_1026 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_read_read_fu_132_p2 == 8'd2))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259 <= pixOut_fu_365_p3;
    end else if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln1913_reg_1026 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_read_read_fu_132_p2 == 8'd2))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259 <= select_ln1913_fu_756_p3;
    end else if ((((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'd0 == and_ln1895_fu_736_p2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_read_read_fu_132_p2 == 8'd1)) | (~(patternId_read_read_fu_132_p2 == 8'd2) & ~(patternId_read_read_fu_132_p2 == 8'd1) & (icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259 <= {{srcImg_dout[23:16]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259 <= ap_phi_reg_pp0_iter1_pix_val_V_2_reg_259;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln1895_fu_736_p2) & (patternId_read_read_fu_132_p2 == 8'd1))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_reg_289 <= pixOut_4_fu_417_p1;
    end else if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln1913_reg_1026 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_read_read_fu_132_p2 == 8'd2))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_reg_289 <= 8'd240;
    end else if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_ln1913_reg_1026 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_read_read_fu_132_p2 == 8'd2))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_reg_289 <= select_ln1913_2_fu_769_p3;
    end else if ((((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'd0 == and_ln1895_fu_736_p2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_read_read_fu_132_p2 == 8'd1)) | (~(patternId_read_read_fu_132_p2 == 8'd2) & ~(patternId_read_read_fu_132_p2 == 8'd1) & (icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_reg_289 <= pixOut_1_fu_648_p1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_val_V_reg_289 <= ap_phi_reg_pp0_iter1_pix_val_V_reg_289;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        boxLeft_fu_116 <= boxHCoord;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (((icmp_ln1855_fu_562_p2 == 1'd0) & (vDir_load_load_fu_555_p1 == 1'd0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)) | ((icmp_ln1859_fu_573_p2 == 1'd0) & (vDir_load_load_fu_555_p1 == 1'd1) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1859_fu_573_p2 == 1'd1) & (vDir_load_load_fu_555_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (patternId_read_read_fu_132_p2 == 8'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1855_fu_562_p2 == 1'd1) & (vDir_load_load_fu_555_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (patternId_read_read_fu_132_p2 == 8'd1)))) begin
        boxLeft_fu_116 <= grp_fu_319_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        boxTop_fu_112 <= boxVCoord;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (((icmp_ln1859_fu_573_p2 == 1'd1) & (vDir_load_load_fu_555_p1 == 1'd1) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)) | ((icmp_ln1855_fu_562_p2 == 1'd0) & (vDir_load_load_fu_555_p1 == 1'd0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1))))) begin
        boxTop_fu_112 <= add_ln1869_fu_600_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (((icmp_ln1859_fu_573_p2 == 1'd0) & (vDir_load_load_fu_555_p1 == 1'd1) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)) | ((icmp_ln1855_fu_562_p2 == 1'd1) & (vDir_load_load_fu_555_p1 == 1'd0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1))))) begin
        boxTop_fu_112 <= sub_ln1871_fu_578_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_182)) begin
        if ((1'b1 == ap_condition_368)) begin
            boxVCoord <= add_ln1869_fu_600_p2;
        end else if ((1'b1 == ap_condition_365)) begin
            boxVCoord <= sub_ln1871_fu_578_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_717)) begin
        if (((icmp_ln1849_fu_544_p2 == 1'd1) & (hDir_load_load_fu_526_p1 == 1'd1))) begin
            hDir <= 1'd0;
        end else if (((icmp_ln1845_fu_533_p2 == 1'd1) & (hDir_load_load_fu_526_p1 == 1'd0))) begin
            hDir <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_717)) begin
        if (((icmp_ln1859_fu_573_p2 == 1'd1) & (vDir_load_load_fu_555_p1 == 1'd1))) begin
            vDir <= 1'd0;
        end else if (((icmp_ln1855_fu_562_p2 == 1'd1) & (vDir_load_load_fu_555_p1 == 1'd0))) begin
            vDir <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_reg_230 <= x_1_reg_980;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln744_fu_489_p2 == 1'd0))) begin
        x_reg_230 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_reg_218 <= y_1_reg_966;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_reg_218 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd2))) begin
        and_ln1913_reg_1019 <= and_ln1913_fu_621_p2;
        or_ln1913_reg_1026 <= or_ln1913_fu_626_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_1_reg_274 <= ap_phi_reg_pp0_iter0_pix_val_V_1_reg_274;
        ap_phi_reg_pp0_iter1_pix_val_V_2_reg_259 <= ap_phi_reg_pp0_iter0_pix_val_V_2_reg_259;
        ap_phi_reg_pp0_iter1_pix_val_V_reg_289 <= ap_phi_reg_pp0_iter0_pix_val_V_reg_289;
        x_1_reg_980 <= x_1_fu_499_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (((icmp_ln1855_fu_562_p2 == 1'd0) & (vDir_load_load_fu_555_p1 == 1'd0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)) | ((icmp_ln1859_fu_573_p2 == 1'd0) & (vDir_load_load_fu_555_p1 == 1'd1) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1859_fu_573_p2 == 1'd1) & (vDir_load_load_fu_555_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (patternId_read_read_fu_132_p2 == 8'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1855_fu_562_p2 == 1'd1) & (vDir_load_load_fu_555_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (patternId_read_read_fu_132_p2 == 8'd1)))) begin
        boxHCoord <= grp_fu_319_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln744_fu_489_p2 == 1'd0))) begin
        icmp_ln1913_reg_975 <= icmp_ln1913_fu_494_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln746_reg_990 <= icmp_ln746_fu_509_p2;
        icmp_ln746_reg_990_pp0_iter1_reg <= icmp_ln746_reg_990;
        trunc_ln746_reg_985 <= trunc_ln746_fu_505_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y_1_reg_966 <= y_1_fu_483_p2;
    end
end

always @ (*) begin
    if ((icmp_ln746_fu_509_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln744_fu_489_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1849_fu_544_p2 == 1'd0) & (hDir_load_load_fu_526_p1 == 1'd1) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)) | ((icmp_ln1845_fu_533_p2 == 1'd1) & (hDir_load_load_fu_526_p1 == 1'd0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)))) begin
        ap_phi_mux_empty_61_phi_fu_245_p8 = 1'd1;
    end else if ((((icmp_ln1845_fu_533_p2 == 1'd0) & (hDir_load_load_fu_526_p1 == 1'd0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)) | ((icmp_ln1849_fu_544_p2 == 1'd1) & (hDir_load_load_fu_526_p1 == 1'd1) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)))) begin
        ap_phi_mux_empty_61_phi_fu_245_p8 = 1'd0;
    end else begin
        ap_phi_mux_empty_61_phi_fu_245_p8 = ap_phi_reg_pp0_iter0_empty_61_reg_242;
    end
end

always @ (*) begin
    if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_x_phi_fu_234_p4 = x_1_reg_980;
    end else begin
        ap_phi_mux_x_phi_fu_234_p4 = x_reg_230;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln744_fu_489_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln746_reg_990_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        outImg_blk_n = outImg_full_n;
    end else begin
        outImg_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln746_reg_990_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outImg_write = 1'b1;
    end else begin
        outImg_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        srcImg_blk_n = srcImg_empty_n;
    end else begin
        srcImg_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln746_reg_990 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        srcImg_read = 1'b1;
    end else begin
        srcImg_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        whiYuv_2_ce0 = 1'b1;
    end else begin
        whiYuv_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln744_fu_489_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln746_fu_509_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln746_fu_509_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1869_fu_600_p2 = (boxTop_fu_112 + zext_ln1867_fu_453_p1);

assign and10_i_fu_397_p2 = (tmp_fu_389_p3 & cmp11_i106_fu_359_p2);

assign and24_i_fu_411_p2 = (tmp_1_fu_403_p3 & cmp11_i106_fu_359_p2);

assign and4_i_fu_383_p2 = (empty_fu_379_p1 & cmp11_i106_fu_359_p2);

assign and_ln1895_1_fu_724_p2 = (rev14_fu_694_p2 & notrhs_fu_700_p2);

assign and_ln1895_2_fu_730_p2 = (xor_ln1890_fu_712_p2 & icmp_ln1890_1_fu_718_p2);

assign and_ln1895_fu_736_p2 = (and_ln1895_2_fu_730_p2 & and_ln1895_1_fu_724_p2);

assign and_ln1899_fu_742_p2 = (trunc_ln746_reg_985 & icmp_fu_431_p2);

assign and_ln1913_fu_621_p2 = (icmp_ln1913_reg_975 & icmp_ln1913_1_fu_616_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln746_reg_990_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (outImg_full_n == 1'b0)) | ((icmp_ln746_reg_990 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (srcImg_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln746_reg_990_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (outImg_full_n == 1'b0)) | ((icmp_ln746_reg_990 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (srcImg_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln746_reg_990_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (outImg_full_n == 1'b0)) | ((icmp_ln746_reg_990 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (srcImg_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = ((icmp_ln746_reg_990 == 1'd0) & (srcImg_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter2 = ((icmp_ln746_reg_990_pp0_iter1_reg == 1'd0) & (outImg_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_182 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_365 = (((icmp_ln1859_fu_573_p2 == 1'd0) & (vDir_load_load_fu_555_p1 == 1'd1) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)) | ((icmp_ln1855_fu_562_p2 == 1'd1) & (vDir_load_load_fu_555_p1 == 1'd0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)));
end

always @ (*) begin
    ap_condition_368 = (((icmp_ln1859_fu_573_p2 == 1'd1) & (vDir_load_load_fu_555_p1 == 1'd1) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)) | ((icmp_ln1855_fu_562_p2 == 1'd0) & (vDir_load_load_fu_555_p1 == 1'd0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (patternId_read_read_fu_132_p2 == 8'd1)));
end

always @ (*) begin
    ap_condition_717 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1840_fu_520_p2 == 1'd1) & (icmp_ln746_fu_509_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (patternId_read_read_fu_132_p2 == 8'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_empty_61_reg_242 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_1_reg_274 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_2_reg_259 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_reg_289 = 'bx;

assign ap_ready = internal_ap_ready;

assign boxBottom_fu_683_p2 = (boxSize + boxTop_fu_112);

assign boxRight_fu_678_p2 = (boxSize + boxLeft_fu_116);

assign cmp11_i106_fu_359_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign cmp13_i_fu_373_p2 = ((colorFormat == 8'd1) ? 1'b1 : 1'b0);

assign empty_62_fu_811_p3 = ((tobool_fu_341_p2[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274 : select_ln1935_fu_804_p3);

assign empty_fu_379_p1 = maskId[0:0];

assign grp_fu_309_p2 = (boxLeft_fu_116 - zext_ln1867_fu_453_p1);

assign grp_fu_314_p2 = (boxLeft_fu_116 + zext_ln1867_fu_453_p1);

assign grp_fu_319_p3 = ((ap_phi_mux_empty_61_phi_fu_245_p8[0:0] == 1'b1) ? grp_fu_309_p2 : grp_fu_314_p2);

assign hDir_load_load_fu_526_p1 = hDir;

assign hMax_fu_347_p2 = (width - boxSize);

assign icmp_fu_431_p2 = ((tmp_2_fu_421_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln1840_fu_520_p2 = ((or_ln1840_fu_514_p2 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1845_fu_533_p2 = ((boxLeft_fu_116 > hMax_fu_347_p2) ? 1'b1 : 1'b0);

assign icmp_ln1849_fu_544_p2 = ((boxLeft_fu_116 < zext_ln1867_1_fu_449_p1) ? 1'b1 : 1'b0);

assign icmp_ln1855_fu_562_p2 = ((boxTop_fu_112 > vMax_fu_353_p2) ? 1'b1 : 1'b0);

assign icmp_ln1859_fu_573_p2 = ((boxTop_fu_112 < zext_ln1867_1_fu_449_p1) ? 1'b1 : 1'b0);

assign icmp_ln1890_1_fu_718_p2 = ((x_reg_230 < boxRight_fu_678_p2) ? 1'b1 : 1'b0);

assign icmp_ln1890_fu_706_p2 = ((x_reg_230 < boxLeft_fu_116) ? 1'b1 : 1'b0);

assign icmp_ln1913_1_fu_616_p2 = ((ap_phi_mux_x_phi_fu_234_p4 != crossHairX) ? 1'b1 : 1'b0);

assign icmp_ln1913_fu_494_p2 = ((y_reg_218 != crossHairY) ? 1'b1 : 1'b0);

assign icmp_ln744_fu_489_p2 = ((y_reg_218 == height) ? 1'b1 : 1'b0);

assign icmp_ln746_fu_509_p2 = ((ap_phi_mux_x_phi_fu_234_p4 == width) ? 1'b1 : 1'b0);

assign notrhs_fu_700_p2 = ((y_reg_218 < boxBottom_fu_683_p2) ? 1'b1 : 1'b0);

assign or_ln1840_fu_514_p2 = (y_reg_218 | ap_phi_mux_x_phi_fu_234_p4);

assign or_ln1913_fu_626_p2 = (cmp11_i106_fu_359_p2 | and_ln1913_fu_621_p2);

assign or_ln1919_fu_631_p2 = (trunc_ln746_fu_505_p1 | cmp13_i_fu_373_p2);

assign outImg_din = {{{outpix_0_2_0_0_0_load_fu_790_p3}, {empty_62_fu_811_p3}}, {outpix_0_0_0_0_0_load_fu_797_p3}};

assign outpix_0_0_0_0_0_load_fu_797_p3 = ((tobool_fu_341_p2[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_pix_val_V_reg_289 : select_ln1933_fu_776_p3);

assign outpix_0_2_0_0_0_load_fu_790_p3 = ((tobool_fu_341_p2[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259 : select_ln1937_fu_783_p3);

assign patternId_read_read_fu_132_p2 = patternId;

assign pixOut_1_fu_648_p1 = srcImg_dout[7:0];

assign pixOut_2_fu_652_p4 = {{srcImg_dout[15:8]}};

assign pixOut_3_fu_662_p4 = {{srcImg_dout[23:16]}};

assign pixOut_4_fu_417_p1 = boxColorR[7:0];

assign pixOut_5_fu_749_p3 = ((and_ln1899_fu_742_p2[0:0] == 1'b1) ? pixOut_6_fu_437_p1 : trunc_ln1899_fu_746_p1);

assign pixOut_6_fu_437_p1 = boxColorB[7:0];

assign pixOut_fu_365_p3 = ((cmp11_i106_fu_359_p2[0:0] == 1'b1) ? 8'd240 : 8'd128);

assign rev14_fu_694_p2 = (ult_fu_688_p2 ^ 1'd1);

assign select_ln1913_1_fu_762_p3 = ((and_ln1913_reg_1019[0:0] == 1'b1) ? pixOut_2_fu_652_p4 : 8'd240);

assign select_ln1913_2_fu_769_p3 = ((and_ln1913_reg_1019[0:0] == 1'b1) ? pixOut_1_fu_648_p1 : 8'd240);

assign select_ln1913_fu_756_p3 = ((and_ln1913_reg_1019[0:0] == 1'b1) ? pixOut_3_fu_662_p4 : pixOut_fu_365_p3);

assign select_ln1919_1_fu_465_p3 = ((cmp13_i_fu_373_p2[0:0] == 1'b1) ? 2'd1 : 2'd2);

assign select_ln1919_fu_636_p3 = ((or_ln1919_fu_631_p2[0:0] == 1'b1) ? select_ln1919_1_fu_465_p3 : 2'd1);

assign select_ln1933_fu_776_p3 = ((and4_i_fu_383_p2[0:0] == 1'b1) ? 8'd0 : ap_phi_reg_pp0_iter2_pix_val_V_reg_289);

assign select_ln1935_fu_804_p3 = ((and10_i_fu_397_p2[0:0] == 1'b1) ? 8'd0 : ap_phi_reg_pp0_iter2_pix_val_V_1_reg_274);

assign select_ln1937_fu_783_p3 = ((and24_i_fu_411_p2[0:0] == 1'b1) ? 8'd0 : ap_phi_reg_pp0_iter2_pix_val_V_2_reg_259);

assign shl_i_fu_441_p3 = {{motionSpeed}, {1'd0}};

assign start_out = real_start;

assign sub_ln1871_fu_578_p2 = (boxTop_fu_112 - zext_ln1867_fu_453_p1);

assign tmp_1_fu_403_p3 = maskId[32'd2];

assign tmp_2_fu_421_p4 = {{colorFormat[7:1]}};

assign tmp_fu_389_p3 = maskId[32'd1];

assign tobool_fu_341_p2 = ((maskId == 8'd0) ? 1'b1 : 1'b0);

assign trunc_ln1899_fu_746_p1 = boxColorG[7:0];

assign trunc_ln746_fu_505_p1 = ap_phi_mux_x_phi_fu_234_p4[0:0];

assign ult_fu_688_p2 = ((y_reg_218 < boxTop_fu_112) ? 1'b1 : 1'b0);

assign vDir_load_load_fu_555_p1 = vDir;

assign vMax_fu_353_p2 = (height - boxSize);

assign whiYuv_2_address0 = zext_ln1919_fu_643_p1;

assign x_1_fu_499_p2 = (ap_phi_mux_x_phi_fu_234_p4 + 16'd1);

assign xor_ln1890_fu_712_p2 = (icmp_ln1890_fu_706_p2 ^ 1'd1);

assign y_1_fu_483_p2 = (y_reg_218 + 16'd1);

assign zext_ln1867_1_fu_449_p1 = shl_i_fu_441_p3;

assign zext_ln1867_fu_453_p1 = motionSpeed;

assign zext_ln1919_fu_643_p1 = select_ln1919_fu_636_p3;

endmodule //zynq_base_v_tpg_0_0_tpgForeground
