# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zynq_constrs.xdc

# Block Designs: bd/zynq_base/zynq_base.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base || ORIG_REF_NAME==zynq_base} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_processing_system7_0_0/zynq_base_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_processing_system7_0_0 || ORIG_REF_NAME==zynq_base_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_clk_wiz_0_0/zynq_base_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_clk_wiz_0_0 || ORIG_REF_NAME==zynq_base_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_v_tc_0_0/zynq_base_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_v_tc_0_0 || ORIG_REF_NAME==zynq_base_v_tc_0_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_v_axi4s_vid_out_0_0/zynq_base_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==zynq_base_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_v_tpg_0_0/zynq_base_v_tpg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_v_tpg_0_0 || ORIG_REF_NAME==zynq_base_v_tpg_0_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_xbar_0/zynq_base_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_xbar_0 || ORIG_REF_NAME==zynq_base_xbar_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_ps7_0_axi_periph_0/zynq_base_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_base_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_rst_clk_wiz_0_74M_0/zynq_base_rst_clk_wiz_0_74M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_rst_clk_wiz_0_74M_0 || ORIG_REF_NAME==zynq_base_rst_clk_wiz_0_74M_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_xlslice_0_0/zynq_base_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_xlslice_0_0 || ORIG_REF_NAME==zynq_base_xlslice_0_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_xlslice_red_0/zynq_base_xlslice_red_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_xlslice_red_0 || ORIG_REF_NAME==zynq_base_xlslice_red_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_xlslice_red1_1/zynq_base_xlslice_red1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_xlslice_red1_1 || ORIG_REF_NAME==zynq_base_xlslice_red1_1} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_axi_vdma_0_0/zynq_base_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_axi_vdma_0_0 || ORIG_REF_NAME==zynq_base_axi_vdma_0_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_xbar_1/zynq_base_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_xbar_1 || ORIG_REF_NAME==zynq_base_xbar_1} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_axi_mem_intercon_1/zynq_base_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_axi_mem_intercon_1 || ORIG_REF_NAME==zynq_base_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_rst_ps7_0_100M_1/zynq_base_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_rst_ps7_0_100M_1 || ORIG_REF_NAME==zynq_base_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_axi_gpio_0_0/zynq_base_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_axi_gpio_0_0 || ORIG_REF_NAME==zynq_base_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_axi_timer_0_0/zynq_base_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_axi_timer_0_0 || ORIG_REF_NAME==zynq_base_axi_timer_0_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_xlconcat_0_0/zynq_base_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_xlconcat_0_0 || ORIG_REF_NAME==zynq_base_xlconcat_0_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_auto_pc_0/zynq_base_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_auto_pc_0 || ORIG_REF_NAME==zynq_base_auto_pc_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_auto_cc_0/zynq_base_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_auto_cc_0 || ORIG_REF_NAME==zynq_base_auto_cc_0} -quiet] -quiet

# IP: bd/zynq_base/ip/zynq_base_auto_pc_1/zynq_base_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_base_auto_pc_1 || ORIG_REF_NAME==zynq_base_auto_pc_1} -quiet] -quiet

# XDC: c:/lab_05b/lab_05.gen/sources_1/bd/zynq_base/zynq_base_ooc.xdc
