# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/lab_05b/lab_05.srcs/sources_1/bd/zynq_base/ip/zynq_base_xbar_0/zynq_base_xbar_0.xci
# IP: The module: 'zynq_base_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/lab_05b/lab_05.gen/sources_1/bd/zynq_base/ip/zynq_base_xbar_0/zynq_base_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_base_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/lab_05b/lab_05.srcs/sources_1/bd/zynq_base/ip/zynq_base_xbar_0/zynq_base_xbar_0.xci
# IP: The module: 'zynq_base_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/lab_05b/lab_05.gen/sources_1/bd/zynq_base/ip/zynq_base_xbar_0/zynq_base_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_base_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
