# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/000 Term 9 000/LBYCPH3/lab_05/lab_05.srcs/sources_1/bd/zynq_base/ip/zynq_base_clk_wiz_0_0/zynq_base_clk_wiz_0_0.xci
# IP: The module: 'zynq_base_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/000 Term 9 000/LBYCPH3/lab_05/lab_05.gen/sources_1/bd/zynq_base/ip/zynq_base_clk_wiz_0_0/zynq_base_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_base_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/000 Term 9 000/LBYCPH3/lab_05/lab_05.gen/sources_1/bd/zynq_base/ip/zynq_base_clk_wiz_0_0/zynq_base_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_base_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/000 Term 9 000/LBYCPH3/lab_05/lab_05.gen/sources_1/bd/zynq_base/ip/zynq_base_clk_wiz_0_0/zynq_base_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_base_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/000 Term 9 000/LBYCPH3/lab_05/lab_05.srcs/sources_1/bd/zynq_base/ip/zynq_base_clk_wiz_0_0/zynq_base_clk_wiz_0_0.xci
# IP: The module: 'zynq_base_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/000 Term 9 000/LBYCPH3/lab_05/lab_05.gen/sources_1/bd/zynq_base/ip/zynq_base_clk_wiz_0_0/zynq_base_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_base_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/000 Term 9 000/LBYCPH3/lab_05/lab_05.gen/sources_1/bd/zynq_base/ip/zynq_base_clk_wiz_0_0/zynq_base_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_base_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/000 Term 9 000/LBYCPH3/lab_05/lab_05.gen/sources_1/bd/zynq_base/ip/zynq_base_clk_wiz_0_0/zynq_base_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_base_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
